sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: daifuyang
    password: 123456
  alioss:
      endpoint: 111
      access-key-id: 1111
      access-key-secret: 1111
      bucket-name: horo-event
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx1c585ff73a3327c3
    secret: c0effd271cef9749928118f0942e2c25
    mchid: ''
    mchSerialNo: ''
    privateKeyFilePath: ''
    apiV3Key: ''
    weChatPayCertFilePath: ''
    notifyUrl: ''
    refundNotifyUrl: ''

